export const TOGGLE_BTN_SCREEN_FIRST = 'TOGGLE_BTN_SCREEN_FIRST';
export const TOGGLE_OPTIONS_SCREEN_FIRST = 'TOGGLE_OPTIONS_SCREEN_FIRST';
export const TOGGLE_BTN_SCREEN_EIGHT = 'TOGGLE_BTN_SCREEN_EIGHT';
export const TOGGLE_OPTIONS_SCREEN_EIGHT = 'TOGGLE_OPTIONS_SCREEN_EIGHT';
